// One source of truth for the Réglages screen, the model picker, and the editor fields, in both UI
// languages. Plain values plus a few small formatters. `copyFor(lang)` selects a locale; `useCopy()`
// reads the active language from LangContext (i18n.ts). `COPY` stays as a French alias so a component
// not yet migrated to useCopy() keeps working (English is added screen by screen).
//
// French strings follow the BASE conventions: tight Swiss-romand punctuation (no space before
// : ; ! ?), tight guillemets «…», no em-dash. English strings use straight quotes and American
// spelling. They are user-facing but live in code, so the .md docs gates do not see them: keep them
// clean by hand.

import type { Lang } from "./i18n.ts";
import { useLang } from "./i18n.ts";
import type { ProviderSettings } from "./api.ts";

// Human labels for the technical provider types: the <select> shows these, the value stays the
// type. `satisfies` makes a missing label a compile error if a provider type is ever added. The
// labels are the same in both languages (brand and protocol names), so one map serves both.
const PROVIDER_TYPE_LABELS = {
  "openai-compatible": "OpenAI / compatible",
  ollama: "Ollama (local)",
  anthropic: "Anthropic",
  google: "Google",
} satisfies Record<ProviderSettings["type"], string>;

// Actionable text for each base-llm failure code (packages/base-llm/src/errors.mjs), per language.
// Open for extension: a new failure mode is one more entry, never a change to the rendering control
// flow; an unknown code falls back to the raw server message at the call site, so nothing is hidden.
export const PROVIDER_ERRORS: Record<string, (env?: string) => string> = {
  "llm.config": (env) => `clé absente: exportez ${env ?? "la variable d'environnement"} dans le terminal qui lance «base studio», puis relancez`,
  "llm.auth": (env) => `clé refusée: vérifiez la valeur de ${env ?? "la variable d'environnement"} côté serveur`,
  "llm.rate_limit": () => "trop de requêtes pour le moment: réessayez dans un instant",
  "llm.network": () => "serveur injoignable: vérifiez l'URL et que le service tourne",
  "llm.timeout": () => "délai dépassé: le serveur a mis trop de temps à répondre",
  "llm.response": () => "réponse inattendue du fournisseur",
};

const PROVIDER_ERRORS_EN: Record<string, (env?: string) => string> = {
  "llm.config": (env) => `key missing: export ${env ?? "the environment variable"} in the terminal that runs "base studio", then restart`,
  "llm.auth": (env) => `key rejected: check the value of ${env ?? "the environment variable"} on the server side`,
  "llm.rate_limit": () => "too many requests right now: try again in a moment",
  "llm.network": () => "server unreachable: check the URL and that the service is running",
  "llm.timeout": () => "timed out: the server took too long to respond",
  "llm.response": () => "unexpected response from the provider",
};

// Map a coded provider failure to its actionable text in the given language, falling back to the raw
// server message when the code is unknown (so nothing is hidden). Shared by the Réglages connection
// test and the chat error path, so the same failure reads the same way wherever it surfaces.
export function providerErrorText(r: { code?: string; env?: string; error?: string }, lang: Lang = "fr"): string {
  const table = lang === "en" ? PROVIDER_ERRORS_EN : PROVIDER_ERRORS;
  const render = r.code ? table[r.code] : undefined;
  return render ? render(r.env) : r.error ?? (lang === "en" ? "unknown error" : "erreur inconnue");
}

const FR = {
  common: {
    add: "Ajouter",
    cancel: "Annuler",
    remove: "Retirer",
    local: "local",
    remote: "distant",
    errorPrefix: "Erreur: ",
    loading: "Chargement…",
    close: "Fermer",
    collapse: "Replier",
    sections: "Sections",
  },
  app: {
    perimeterToConfigure: (label: string) => `${label} · dossier à configurer`,
    perimeterWorkspace: (label: string, n: number) => `${label} · ${n} dossier${n > 1 ? "s" : ""}`,
    langFr: "Français",
    langEn: "English",
    footerPre: "Un projet d'",
    footerLink: "AI Swiss",
    footerMid: ", association suisse à but non lucratif · cas d'usage en partenariat avec ",
    footerLink2: "Innovaud",
    footerEnd: ".",
    brandTitle: "Un projet d'AI Swiss",
  },
  settings: {
    title: "Réglages",
    description: "Connectez vos modèles et choisissez ceux qu'utilisent le chat et les évaluations.",
    saved: "Enregistré.",
    location: {
      summary: "Où sont stockés ces réglages?",
      root: "Réglages de ce dossier: ",
      workspace: "Réglages de cet espace de travail, partagés par ses dossiers: ",
      secretsNote: ". Aucun secret n'y est écrit; les clés API vivent dans l'environnement du serveur.",
      defaultFile: ".ai/studio.settings.json",
    },
    models: {
      title: "Modèles",
      description: "Les modèles que Studio peut utiliser, et d'où ils viennent.",
    },
    defaults: {
      title: "Modèles par défaut",
      description: "Les modèles présélectionnés quand vous lancez une évaluation.",
      runner: { label: "Utilisateur simulé", help: "Le modèle qui joue l'utilisateur face à votre assistant pendant une évaluation." },
      judge: { label: "Juge", help: "Le modèle qui note les réponses de votre assistant selon vos critères." },
    },
    routing: {
      title: "Routage / Voie 2",
      description: "Optionnel, pour un grand BASE: les embeddings retrouvent quelques candidats, un petit modèle choisit. Un petit BASE n'en a pas besoin; la Voie 1 (l'assistant lit l'index) suffit.",
      both: "La Voie 2 s'active seulement quand les deux modèles sont renseignés. Un seul ne fait rien; vide partout, c'est la Voie 1 par défaut.",
      embedding: { label: "Modèle d'embedding", help: "Étape 1: il retrouve les quelques process les plus proches de la demande. Un modèle local (Ollama) suffit." },
      refiner: { label: "Modèle raffineur", help: "Étape 2: un petit modèle lit ces candidats et choisit le bon, ou demande une précision." },
      k: { label: "Candidats", help: "Combien de candidats le raffineur voit (un nombre, pas un seuil). 10 par défaut." },
      setup: "Besoin d'aide pour installer les modèles? Demandez à votre assistant: «active la Voie 2».",
    },
    providerType: PROVIDER_TYPE_LABELS,
    provider: {
      testing: "test en cours…",
      testOk: (latencyMs: number, url?: string) => `OK, ${latencyMs} ms${url ? ` (${url})` : ""}`,
      testFail: (r: { code?: string; env?: string; error?: string }) => `échec: ${providerErrorText(r, "fr")}`,
      key: {
        none: "clé: aucune requise",
        detected: (env: string) => `clé détectée (${env})`,
        missing: (env?: string) => `clé absente: exportez ${env ?? "la variable d'environnement"} côté serveur`,
      },
      defaultUrl: "URL par défaut",
      discovered: "Modèles découverts",
      noModels: "(aucun)",
      refresh: "Actualiser",
      test: "Tester la connexion",
      renamePlaceholder: "nom court (ex: rapide)",
      renameAria: (model: string) => `Nom d'affichage pour ${model}`,
      more: (n: number) => `+${n}`,
    },
    addProvider: {
      trigger: "+ Ajouter un fournisseur",
      ariaLabel: "Ajouter un fournisseur",
      needId: "Donnez d'abord un identifiant",
      id: { label: "Identifiant", placeholder: "ex: openai", help: "Un nom court pour ce fournisseur, comme vous voudrez l'appeler." },
      type: { label: "Type", help: "La famille d'API du fournisseur. Ollama tourne sur votre machine; les autres sont des services distants." },
      baseUrl: { label: "URL de base", optional: "(optionnel)", placeholder: "https://…", help: "Laissez vide pour l'adresse standard du fournisseur." },
      apiKeyEnv: { label: "Variable d'env. de la clé", optional: "(optionnel)", placeholder: "ex: OPENAI_API_KEY", help: "Le NOM de la variable d'environnement, jamais la clé elle-même." },
    },
    firstModel: {
      aria: "Connecter un premier modèle",
      title: "Connectez un premier modèle (≈ 2 min)",
      intro: "Une évaluation, comme le chat, a besoin d'un modèle. Trois chemins, du plus simple au plus puissant.",
      ollamaTitle: "🟢 Ollama, sur votre machine (gratuit, privé, sans clé)",
      ollamaReady: "Ollama tourne ici. Un clic et c'est prêt.",
      ollamaConnect: "Connecter Ollama",
      ollamaInstallPre: "Installez l'application ",
      ollamaInstallMid: ", lancez-la, puis téléchargez un modèle léger (par ex. ",
      ollamaInstallSize: ", ~5 Go). Revenez ici et",
      ollamaReload: " rechargez la page",
      ollamaReloadPost: ": ce bloc proposera «Connecter Ollama».",
      keyTitle: "🔑 Une clé OpenAI ou Anthropic",
      keyIntroPre: "Obtenez une clé sur la console du fournisseur (compte + carte requis), puis donnez-la au serveur, ",
      keyIntroStrong: "jamais à cet écran",
      keyIntroPost: ". Deux façons:",
      keyTerminalPre: "Dans le terminal où vous lancez ",
      keyTerminalPost: " puis relancez. (Pour la rendre permanente: ajoutez-la à votre profil shell.)",
      keyAskPre: "Ou demandez à votre outil IA: ",
      keyAskEm: "«configure la variable OPENAI_API_KEY avec ma clé et relance base studio»",
      keyAskPost: ".",
      keyAfter:
        "Ensuite, ajoutez le fournisseur correspondant ci-dessous (son champ «variable d'env.» = le NOM de la variable, jamais la clé).",
      compatTitle: "🔌 Un serveur compatible OpenAI que vous connaissez",
      compatBody: "Renseignez son URL et, si besoin, la variable d'environnement de sa clé dans le formulaire ci-dessous.",
    },
  },
  picker: {
    placeholder: "choisir un modèle…",
    filterPlaceholder: "filtrer les modèles…",
    filterAria: "Filtrer les modèles",
    listAria: "Modèles",
    offline: "hors ligne",
    empty: "Aucun modèle. Configurez un fournisseur.",
    useAnyway: (label: string) => `Utiliser «${label}» quand même`,
    configure: "Configurer les fournisseurs…",
  },
  eval: {
    jsonStrict: "Réponse structurée (JSON)",
    jsonStrictHelp: "Demande au modèle un format de réponse structuré (JSON), plus fiable à interpréter. Laissez coché si vous n'êtes pas sûr.",
    judgeNote: "Lecture d'un modèle-juge: un signal à vérifier, pas une preuve.",
    confidence: "confiance du juge",
    drawerAria: "Lancer une évaluation",
    evaluate: "▶ Évaluer",
    closeTitle: (combo: string) => `Fermer (${combo})`,
    tickProcesses: "Cochez les process à évaluer. Un utilisateur simulé les joue, un juge note chaque conversation.",
    legend: "Que faut-il évaluer?",
    noProcesses: "Aucun process à évaluer dans cet espace.",
    allProcesses: "Tous les process",
    simulatedUser: "Utilisateur simulé",
    judge: "Juge",
    launch: (count: number): string => (count > 1 ? `Lancer ${count} évaluations` : "Lancer l'évaluation"),
    serial: "Les évaluations s'enchaînent, une à la fois · les clés restent côté serveur.",
  },
  monitor: {
    back: "← Retour à Parcourir",
    title: "Évaluations",
    sub: "Un utilisateur simulé joue vos scénarios contre un process; un juge indépendant note chaque conversation. Sa note est la lecture d'un modèle-juge, à vérifier: un signal, pas un verdict établi.",
    progress: (batchIndex: number, batchCount: number, done: number, total: number | string) =>
      `${batchCount > 1 ? `process ${batchIndex + 1}/${batchCount} · ` : ""}⏳ scénario ${done + 1}/${total}`,
    simulations: "Simulations",
    runs: (n: number) => `Exécutions (${n})`,
    scenarioInProgress: "Scénario en cours",
    emptyFiltered: "Aucune exécution pour cette sélection: élargissez la période ou retirez un filtre.",
    heroAria: "Première évaluation",
    heroTitle: "Mesurez un process avant de l'expédier",
    heroBody:
      "Choisissez un process et quelques scénarios: un utilisateur simulé les joue, un juge indépendant note chaque conversation, et vous obtenez un taux de réussite et les modes d'échec à corriger.",
    heroLaunch: "Lancer votre première évaluation",
    heroNoModel: "Pas encore de modèle? Connecter un modèle (≈ 2 min)",
  },
  runcard: {
    runAria: (id: string) => `Exécution ${id}`,
    turns: (n: number) => `tour${n > 1 ? "s" : ""}`,
    limitation: (tool: string) => `limitation: ${tool}`,
    noVerdict: "Pas de verdict (run en erreur).",
    contextPack: (sections: number, approx: boolean, withheld: number, unresolved: number) =>
      `Contexte injecté: pack (${sections} fichier${sections > 1 ? "s" : ""}` +
      `${approx ? ", référence imparfaite ≈" : ""}` +
      `${withheld ? `, ${withheld} retenu(s) (non transmis au modèle distant)` : ""}` +
      `${unresolved ? `, ${unresolved} introuvable(s)` : ""})`,
    transcript: "Transcription",
    noText: "(pas de texte)",
    denied: "refusé",
    openProcess: "Ouvrir le process ▸",
    relaunch: "Relancer",
    relaunchOther: "Relancer avec un autre modèle",
    fix: (hint: string) => `Correction: ${hint}`,
    evidence: (turn: number, quote: string, why: string) => `tour ${turn}: «${quote}» (${why})`,
  },
  browse: {
    searchAria: "Rechercher une ressource",
    searchPlaceholder: "Rechercher…",
    workspaceHeader: "Espace de travail",
    searchAllFolders: "Chercher dans tous les dossiers",
    searchEverywhere: "Chercher partout",
    widenAllFolders: "Élargir à tous les dossiers",
    widenWholeSpace: "Élargir à tout l'espace",
    scopeWorkspace: (label: string, n: number) => `${label}: ${n} dossiers`,
    resultsFor: (count: number, query: string) => `${count} résultat${count === 1 ? "" : "s"} pour «${query}»`,
    resources: (count: number) => `${count} ressource${count === 1 ? "" : "s"}`,
    scopeLabel: " · portée: ",
    streamKeys: (does: string) => does,
    openCollapse: "ouvrir / replier",
  },
  cardStream: {
    nothingFor: (query: string, scope: string) => `Rien pour «${query}» sous «${scope}».`,
    noneOfTypes: (scope: string) => `Aucune ressource des types cochés sous «${scope}».`,
    none: (scope: string) => `Aucune ressource sous «${scope}».`,
    root: "la racine",
    checkAll: "Tout cocher",
  },
  card: {
    when: (text: string) => `Quand: ${text}`,
    why: (reasons: string) => `pourquoi: ${reasons}`,
    errors: "erreurs",
    applied: "Modification appliquée.",
    line: (line: number, message: string) => `ligne ${line}: ${message}`,
    evaluate: "Évaluer ▶",
    editWithAi: "Éditer avec l'IA",
    collapseTitle: (combo: string) => `Replier (${combo})`,
    detailsSummary: "Détails (métadonnées)",
    requiredLegendPre: "Les champs marqués d'un ",
    requiredLegendPost: " sont obligatoires.",
    bodyAria: "Contenu du document",
    dirtyDot: "● Modifications non écrites",
    proposeChanges: "Proposer les changements",
  },
  chat: {
    noModel: "Aucun modèle connecté.",
    connectModel: "Connecter un modèle (≈ 2 min)",
    panelAria: "Chat d'édition",
    who: (isUser: boolean): string => (isUser ? "Vous" : "Modèle"),
    inputAria: "Demander une modification",
    inputPlaceholder: "Demander une modification…",
    title: "Chat",
    memory: (n: number) => `Mémoire: ${n} message${n > 1 ? "s" : ""} résumé${n > 1 ? "s" : ""}`,
    withheld: (notice: string) => `retenu: ${notice}`,
    proposal: (hunks: number, additions: number, deletions: number) =>
      `± Proposition · ${hunks} bloc${hunks > 1 ? "s" : ""} · +${additions} −${deletions}`,
    seeInDocument: "voir dans le document ↩",
  },
  terrain: {
    aria: "Frictions à traiter",
    title: "À traiter",
    summary: (n: number) =>
      `${n} friction${n > 1 ? "s" : ""} signalée${n > 1 ? "s" : ""} sur le terrain: un correctif en attente, à valider par le diff habituel.`,
    open: "ouvert",
    field: "terrain",
    quote: (text: string) => `«${text}»`,
    reportedVia: (reported: string, via: string) => `${reported} · via ${via}`,
    commitWrite: "Valider et écrire",
    openProcess: "Ouvrir le process ▸",
    evaluate: "Évaluer ▶",
    markResolved: "Marquer résolu",
  },
  diff: {
    proposedAria: (additions: number, deletions: number) => `Modifications proposées: +${additions} −${deletions}`,
    noChange: "(aucun changement)",
    identicalLines: (n: number) => `⋯ ${n} lignes identiques`,
    reviewAria: "Revue des modifications",
    block: (index: number, total: number) => `bloc ${index}/${total}`,
    keep: "Garder",
    undo: "Annuler",
    nothingWritten: "Rien n'est écrit tant que vous ne validez pas.",
    apply: (picked: number, multiple: boolean): string => (multiple ? `Appliquer ${picked} bloc${picked > 1 ? "s" : ""}` : "Appliquer"),
    refuse: "Refuser",
  },
  filter: {
    legend: "Filtres",
    allResources: "Toutes les ressources",
    noFilter: "Aucun filtre: structure complète",
    runsAria: "Filtres des exécutions",
    searchTranscripts: "Rechercher dans les transcriptions",
    searchTranscriptsPlaceholder: "Rechercher dans les transcriptions…",
    process: "Process",
    verdict: "Verdict",
    failureMode: "Mode d'échec",
    model: "Modèle",
    period: "Période",
    days: (n: number) => `${n} jours`,
    all: "Tout",
    reset: "Réinitialiser",
    removeFilter: (label: string) => `Retirer le filtre ${label}`,
    chipValue: (label: string, value: string) => `${label}: ${value}`,
  },
  pulse: {
    aria: "Pulse des évaluations",
    noneInPeriod: "Aucune exécution sur la période:",
    showAll: "tout afficher",
    successRate: (total: number) => `de réussite · ${total} exécution${total > 1 ? "s" : ""}`,
    lastDays: (days: number) => ` · ${days} derniers jours`,
    olderOutOfScope: (n: number) => ` · +${n} plus anciennes hors champ`,
    pts: (delta: number) => `${delta >= 0 ? "+" : ""}${delta} pts`,
  },
  tree: {
    filesAria: "Fichiers",
    frontmatterErrors: "erreurs de frontmatter",
  },
  doctor: {
    summary: (signals: number, errors: number) =>
      `doctor: ${signals} signal${signals > 1 ? "s" : ""}${errors ? ` (${errors} erreur${errors > 1 ? "s" : ""})` : ""}`,
  },
  file: {
    kind: "fichier",
    readOnly: "Lecture seule: ce fichier n'est pas une ressource BASE.",
  },
  welcome: {
    heroTitle: "Bienvenue dans BASE Studio",
    step1Title: "Créer la structure de départ",
    step1Body: (n: number) =>
      `${n} fichier${n > 1 ? "s" : ""} dans ce dossier. Rien n'est écrit avant votre clic: dépliez pour voir le contenu exact.`,
    planAria: "Fichiers à créer",
    creating: "Création…",
    createFiles: "Créer ces fichiers",
    step2Title: "Ouvrir dans votre outil IA",
    step2Pre: "C'est là que tout se passe. ",
    step2Strong: "Votre outil IA est l'expérience; Studio est l'atelier.",
    step2Post: " Une fois la structure créée, ouvrez ce dossier dans votre outil IA et faites-lui lire ",
    step2Code: "BASE_BOOTSTRAP.md",
    step2End: ".",
    step2Prompt: (path: string) => `Ouvre le dossier "${path}", puis lis BASE_BOOTSTRAP.md.`,
    step3Title: "Aller plus loin",
    importStrong: "Importer vos documents:",
    importPre: " demandez à votre assistant «importer mes procédures existantes»: le process ",
    importCode: "importer-l-existant",
    importPost: " propose chaque conversion en diff, rien n'est écrit sans vous.",
    scratchStrong: "Partir de zéro:",
    scratchPre: " le guide de démarrage explique la structure d'un agent (AGENT.md, process, compétences): ",
    scratchCode: "docs/start/quickstart.md",
    scratchPost: ".",
    copied: "copié ✓",
    copy: "copier",
    diagCollection: (n: number, label: string) =>
      `${n} assistants BASE détectés dans «${label}»: un fichier workspace les réunira.`,
    diagLooseSkills: (label: string) =>
      `Vous avez déjà des fichiers SKILL.md dans «${label}»: vous parlez déjà BASE. Il ne manque que la structure minimale.`,
    diagLooseMarkdown: (count: number, label: string) =>
      `${count} fichier${count > 1 ? "s" : ""} Markdown dans «${label}», sans structure BASE pour l'instant.`,
    diagEmpty: (label: string) => `«${label}» est vide: on part du point de départ minimal: un agent.`,
    diagDefault: (label: string) => `«${label}» n'est pas encore configuré pour BASE.`,
  },
  workspace: {
    drawerAria: "Gérer l'espace de travail",
    title: "Espace de travail",
    intro: "Les dossiers de cet espace. Le dossier par défaut s'ouvre en premier.",
    folderNameAria: (i: number) => `Nom du dossier ${i}`,
    defaultLabel: "défaut",
    addPathAria: "Chemin d'un dossier à ajouter",
    addPathPlaceholder: "chemin d'un dossier BASE (ex. clients/acme)",
    addFolder: "+ Ajouter un dossier",
    save: "Enregistrer l'espace",
    notePre: "Chaque dossier doit être un BASE (un ",
    noteMid: "). Écrit dans ",
    notePost: ".",
    defaultFolderId: "dossier",
  },
  field: {
    listPlaceholder: "valeurs séparées par des virgules",
    requiredTip: "champ obligatoire",
    requiredAria: "obligatoire",
    structural: " (structurel)",
  },
};

const EN: typeof FR = {
  common: {
    add: "Add",
    cancel: "Cancel",
    remove: "Remove",
    local: "local",
    remote: "remote",
    errorPrefix: "Error: ",
    loading: "Loading…",
    close: "Close",
    collapse: "Collapse",
    sections: "Sections",
  },
  app: {
    perimeterToConfigure: (label: string) => `${label} · folder to configure`,
    perimeterWorkspace: (label: string, n: number) => `${label} · ${n} folder${n > 1 ? "s" : ""}`,
    langFr: "Français",
    langEn: "English",
    footerPre: "A project of ",
    footerLink: "AI Swiss",
    footerMid: ", a Swiss non-profit · use cases in partnership with ",
    footerLink2: "Innovaud",
    footerEnd: ".",
    brandTitle: "A project of AI Swiss",
  },
  settings: {
    title: "Settings",
    description: "Connect your models and choose which ones the chat and evaluations use.",
    saved: "Saved.",
    location: {
      summary: "Where are these settings stored?",
      root: "Settings for this folder: ",
      workspace: "Settings for this workspace, shared by its folders: ",
      secretsNote: ". No secret is written here; API keys live in the server's environment.",
      defaultFile: ".ai/studio.settings.json",
    },
    models: {
      title: "Models",
      description: "The models Studio can use, and where they come from.",
    },
    defaults: {
      title: "Default models",
      description: "The models preselected when you launch an evaluation.",
      runner: { label: "Simulated user", help: "The model that plays the user facing your assistant during an evaluation." },
      judge: { label: "Judge", help: "The model that scores your assistant's answers against your criteria." },
    },
    routing: {
      title: "Routing / Track 2",
      description: "Optional, for a large BASE: embeddings retrieve a few candidates, a small model picks. A small BASE does not need it; Track 1 (the assistant reads the index) is enough.",
      both: "Track 2 turns on only when both models are set. One alone does nothing; empty everywhere is Track 1 by default.",
      embedding: { label: "Embedding model", help: "Step 1: it retrieves the few processes closest to the request. A local model (Ollama) is enough." },
      refiner: { label: "Refiner model", help: "Step 2: a small model reads those candidates and picks the right one, or asks for a clarification." },
      k: { label: "Candidates", help: "How many candidates the refiner sees (a number, not a threshold). 10 by default." },
      setup: "Need help installing the models? Ask your assistant: \"turn on Track 2\".",
    },
    providerType: PROVIDER_TYPE_LABELS,
    provider: {
      testing: "testing…",
      testOk: (latencyMs: number, url?: string) => `OK, ${latencyMs} ms${url ? ` (${url})` : ""}`,
      testFail: (r: { code?: string; env?: string; error?: string }) => `failed: ${providerErrorText(r, "en")}`,
      key: {
        none: "key: none required",
        detected: (env: string) => `key detected (${env})`,
        missing: (env?: string) => `key missing: export ${env ?? "the environment variable"} on the server side`,
      },
      defaultUrl: "Default URL",
      discovered: "Discovered models",
      noModels: "(none)",
      refresh: "Refresh",
      test: "Test the connection",
      renamePlaceholder: "short name (e.g. fast)",
      renameAria: (model: string) => `Display name for ${model}`,
      more: (n: number) => `+${n}`,
    },
    addProvider: {
      trigger: "+ Add a provider",
      ariaLabel: "Add a provider",
      needId: "Give an identifier first",
      id: { label: "Identifier", placeholder: "e.g. openai", help: "A short name for this provider, whatever you want to call it." },
      type: { label: "Type", help: "The provider's API family. Ollama runs on your machine; the others are remote services." },
      baseUrl: { label: "Base URL", optional: "(optional)", placeholder: "https://…", help: "Leave empty for the provider's standard address." },
      apiKeyEnv: { label: "Key env variable", optional: "(optional)", placeholder: "e.g. OPENAI_API_KEY", help: "The NAME of the environment variable, never the key itself." },
    },
    firstModel: {
      aria: "Connect a first model",
      title: "Connect a first model (about 2 min)",
      intro: "An evaluation, like the chat, needs a model. Three paths, from the simplest to the most powerful.",
      ollamaTitle: "🟢 Ollama, on your machine (free, private, no key)",
      ollamaReady: "Ollama is running here. One click and you are ready.",
      ollamaConnect: "Connect Ollama",
      ollamaInstallPre: "Install the ",
      ollamaInstallMid: " app, launch it, then download a small model (for example ",
      ollamaInstallSize: ", about 5 GB). Come back here and",
      ollamaReload: " reload the page",
      ollamaReloadPost: ': this block will then offer "Connect Ollama".',
      keyTitle: "🔑 An OpenAI or Anthropic key",
      keyIntroPre: "Get a key from the provider's console (account plus card required), then give it to the server, ",
      keyIntroStrong: "never to this screen",
      keyIntroPost: ". Two ways:",
      keyTerminalPre: "In the terminal where you run ",
      keyTerminalPost: " then restart. (To make it permanent: add it to your shell profile.)",
      keyAskPre: "Or ask your AI tool: ",
      keyAskEm: '"set the OPENAI_API_KEY variable to my key and restart base studio"',
      keyAskPost: ".",
      keyAfter:
        'Then add the matching provider below (its "env variable" field = the NAME of the variable, never the key).',
      compatTitle: "🔌 An OpenAI-compatible server you know",
      compatBody: "Enter its URL and, if needed, the environment variable of its key in the form below.",
    },
  },
  picker: {
    placeholder: "choose a model…",
    filterPlaceholder: "filter models…",
    filterAria: "Filter models",
    listAria: "Models",
    offline: "offline",
    empty: "No models. Configure a provider.",
    useAnyway: (label: string) => `Use "${label}" anyway`,
    configure: "Configure providers…",
  },
  eval: {
    jsonStrict: "Structured response (JSON)",
    jsonStrictHelp: "Asks the model for a structured response format (JSON), more reliable to parse. Leave checked if unsure.",
    judgeNote: "A judge model's read: a signal to verify, not a proof.",
    confidence: "judge confidence",
    drawerAria: "Launch an evaluation",
    evaluate: "▶ Evaluate",
    closeTitle: (combo: string) => `Close (${combo})`,
    tickProcesses: "Check the processes to evaluate. A simulated user plays them, a judge scores each conversation.",
    legend: "What should be evaluated?",
    noProcesses: "No process to evaluate in this space.",
    allProcesses: "All processes",
    simulatedUser: "Simulated user",
    judge: "Judge",
    launch: (count: number) => (count > 1 ? `Launch ${count} evaluations` : "Launch the evaluation"),
    serial: "Evaluations run in sequence, one at a time · keys stay on the server.",
  },
  monitor: {
    back: "← Back to Browse",
    title: "Evaluations",
    sub: "A simulated user plays your scenarios against a process; an independent judge scores each conversation. Its score is a judge model's read, to verify: a signal, not a settled verdict.",
    progress: (batchIndex: number, batchCount: number, done: number, total: number | string) =>
      `${batchCount > 1 ? `process ${batchIndex + 1}/${batchCount} · ` : ""}⏳ scenario ${done + 1}/${total}`,
    simulations: "Simulations",
    runs: (n: number) => `Runs (${n})`,
    scenarioInProgress: "Scenario in progress",
    emptyFiltered: "No run for this selection: widen the period or remove a filter.",
    heroAria: "First evaluation",
    heroTitle: "Measure a process before you ship it",
    heroBody:
      "Pick a process and a few scenarios: a simulated user plays them, an independent judge scores each conversation, and you get a success rate and the failure modes to fix.",
    heroLaunch: "Launch your first evaluation",
    heroNoModel: "No model yet? Connect a model (about 2 min)",
  },
  runcard: {
    runAria: (id: string) => `Run ${id}`,
    turns: (n: number) => `turn${n > 1 ? "s" : ""}`,
    limitation: (tool: string) => `limitation: ${tool}`,
    noVerdict: "No verdict (run errored).",
    contextPack: (sections: number, approx: boolean, withheld: number, unresolved: number) =>
      `Injected context: pack (${sections} file${sections > 1 ? "s" : ""}` +
      `${approx ? ", imperfect reference ≈" : ""}` +
      `${withheld ? `, ${withheld} withheld (not sent to the remote model)` : ""}` +
      `${unresolved ? `, ${unresolved} not found` : ""})`,
    transcript: "Transcript",
    noText: "(no text)",
    denied: "denied",
    openProcess: "Open the process ▸",
    relaunch: "Relaunch",
    relaunchOther: "Relaunch with another model",
    fix: (hint: string) => `Fix: ${hint}`,
    evidence: (turn: number, quote: string, why: string) => `turn ${turn}: "${quote}" (${why})`,
  },
  browse: {
    searchAria: "Search a resource",
    searchPlaceholder: "Search…",
    workspaceHeader: "Workspace",
    searchAllFolders: "Search in all folders",
    searchEverywhere: "Search everywhere",
    widenAllFolders: "Widen to all folders",
    widenWholeSpace: "Widen to the whole space",
    scopeWorkspace: (label: string, n: number) => `${label}: ${n} folders`,
    resultsFor: (count: number, query: string) => `${count} result${count === 1 ? "" : "s"} for "${query}"`,
    resources: (count: number) => `${count} resource${count === 1 ? "" : "s"}`,
    scopeLabel: " · scope: ",
    streamKeys: (does: string) => does,
    openCollapse: "open / collapse",
  },
  cardStream: {
    nothingFor: (query: string, scope: string) => `Nothing for "${query}" under "${scope}".`,
    noneOfTypes: (scope: string) => `No resource of the checked types under "${scope}".`,
    none: (scope: string) => `No resource under "${scope}".`,
    root: "the root",
    checkAll: "Check all",
  },
  card: {
    when: (text: string) => `When: ${text}`,
    why: (reasons: string) => `why: ${reasons}`,
    errors: "errors",
    applied: "Change applied.",
    line: (line: number, message: string) => `line ${line}: ${message}`,
    evaluate: "Evaluate ▶",
    editWithAi: "Edit with AI",
    collapseTitle: (combo: string) => `Collapse (${combo})`,
    detailsSummary: "Details (metadata)",
    requiredLegendPre: "Fields marked with a ",
    requiredLegendPost: " are required.",
    bodyAria: "Document content",
    dirtyDot: "● Unwritten changes",
    proposeChanges: "Propose the changes",
  },
  chat: {
    noModel: "No model connected.",
    connectModel: "Connect a model (about 2 min)",
    panelAria: "Editing chat",
    who: (isUser: boolean) => (isUser ? "You" : "Model"),
    inputAria: "Ask for a change",
    inputPlaceholder: "Ask for a change…",
    title: "Chat",
    memory: (n: number) => `Memory: ${n} message${n > 1 ? "s" : ""} summarized`,
    withheld: (notice: string) => `withheld: ${notice}`,
    proposal: (hunks: number, additions: number, deletions: number) =>
      `± Proposal · ${hunks} block${hunks > 1 ? "s" : ""} · +${additions} −${deletions}`,
    seeInDocument: "see in the document ↩",
  },
  terrain: {
    aria: "Frictions to handle",
    title: "To handle",
    summary: (n: number) =>
      `${n} friction${n > 1 ? "s" : ""} reported in the field: a pending fix, to confirm through the usual diff.`,
    open: "open",
    field: "field",
    quote: (text: string) => `"${text}"`,
    reportedVia: (reported: string, via: string) => `${reported} · via ${via}`,
    commitWrite: "Confirm and write",
    openProcess: "Open the process ▸",
    evaluate: "Evaluate ▶",
    markResolved: "Mark resolved",
  },
  diff: {
    proposedAria: (additions: number, deletions: number) => `Proposed changes: +${additions} −${deletions}`,
    noChange: "(no change)",
    identicalLines: (n: number) => `⋯ ${n} identical lines`,
    reviewAria: "Change review",
    block: (index: number, total: number) => `block ${index}/${total}`,
    keep: "Keep",
    undo: "Undo",
    nothingWritten: "Nothing is written until you confirm.",
    apply: (picked: number, multiple: boolean) => (multiple ? `Apply ${picked} block${picked > 1 ? "s" : ""}` : "Apply"),
    refuse: "Refuse",
  },
  filter: {
    legend: "Filters",
    allResources: "All resources",
    noFilter: "No filter: full structure",
    runsAria: "Run filters",
    searchTranscripts: "Search the transcripts",
    searchTranscriptsPlaceholder: "Search the transcripts…",
    process: "Process",
    verdict: "Verdict",
    failureMode: "Failure mode",
    model: "Model",
    period: "Period",
    days: (n: number) => `${n} days`,
    all: "All",
    reset: "Reset",
    removeFilter: (label: string) => `Remove the ${label} filter`,
    chipValue: (label: string, value: string) => `${label}: ${value}`,
  },
  pulse: {
    aria: "Evaluations pulse",
    noneInPeriod: "No run in the period:",
    showAll: "show all",
    successRate: (total: number) => `success rate · ${total} run${total > 1 ? "s" : ""}`,
    lastDays: (days: number) => ` · last ${days} days`,
    olderOutOfScope: (n: number) => ` · +${n} older out of scope`,
    pts: (delta: number) => `${delta >= 0 ? "+" : ""}${delta} pts`,
  },
  tree: {
    filesAria: "Files",
    frontmatterErrors: "frontmatter errors",
  },
  doctor: {
    summary: (signals: number, errors: number) =>
      `doctor: ${signals} signal${signals > 1 ? "s" : ""}${errors ? ` (${errors} error${errors > 1 ? "s" : ""})` : ""}`,
  },
  file: {
    kind: "file",
    readOnly: "Read-only: this file is not a BASE resource.",
  },
  welcome: {
    heroTitle: "Welcome to BASE Studio",
    step1Title: "Create the starting structure",
    step1Body: (n: number) =>
      `${n} file${n > 1 ? "s" : ""} in this folder. Nothing is written before your click: expand to see the exact content.`,
    planAria: "Files to create",
    creating: "Creating…",
    createFiles: "Create these files",
    step2Title: "Open in your AI tool",
    step2Pre: "This is where everything happens. ",
    step2Strong: "Your AI tool is the experience; Studio is the workshop.",
    step2Post: " Once the structure is created, open this folder in your AI tool and ask it to read ",
    step2Code: "BASE_BOOTSTRAP.md",
    step2End: ".",
    step2Prompt: (path: string) => `Open the folder "${path}", then read BASE_BOOTSTRAP.md.`,
    step3Title: "Go further",
    importStrong: "Import your documents:",
    importPre: ' ask your assistant "import my existing procedures": the ',
    importCode: "importer-l-existant",
    importPost: " process proposes each conversion as a diff, nothing is written without you.",
    scratchStrong: "Start from scratch:",
    scratchPre: " the quickstart guide explains the structure of an agent (AGENT.md, processes, competences): ",
    scratchCode: "docs/start/quickstart.md",
    scratchPost: ".",
    copied: "copied ✓",
    copy: "copy",
    diagCollection: (n: number, label: string) =>
      `${n} BASE assistants detected in "${label}": a workspace file will bring them together.`,
    diagLooseSkills: (label: string) =>
      `You already have SKILL.md files in "${label}": you already speak BASE. Only the minimal structure is missing.`,
    diagLooseMarkdown: (count: number, label: string) =>
      `${count} Markdown file${count > 1 ? "s" : ""} in "${label}", without a BASE structure for now.`,
    diagEmpty: (label: string) => `"${label}" is empty: we start from the minimal starting point: an agent.`,
    diagDefault: (label: string) => `"${label}" is not configured for BASE yet.`,
  },
  workspace: {
    drawerAria: "Manage workspace",
    title: "Workspace",
    intro: "The folders of this space. The default folder opens first.",
    folderNameAria: (i: number) => `Folder name ${i}`,
    defaultLabel: "default",
    addPathAria: "Path of a folder to add",
    addPathPlaceholder: "path of a BASE folder (e.g. clients/acme)",
    addFolder: "+ Add a folder",
    save: "Save the space",
    notePre: "Each folder must be a BASE (a ",
    noteMid: "). Written to ",
    notePost: ".",
    defaultFolderId: "folder",
  },
  field: {
    listPlaceholder: "comma-separated values",
    requiredTip: "required field",
    requiredAria: "required",
    structural: " (structural)",
  },
};

const CATALOG: Record<Lang, typeof FR> = { fr: FR, en: EN };

/** The copy catalog for a language. */
export function copyFor(lang: Lang): typeof FR {
  return CATALOG[lang];
}

/** The copy catalog for the active UI language (from LangContext). */
export function useCopy(): typeof FR {
  return copyFor(useLang());
}

// French alias, for components not yet migrated to useCopy() and for tests that assert French.
export const COPY = FR;
