// Canonical entry-point body: the single source of truth for every harness bootstrap
// (CLAUDE.md, BASE_BOOTSTRAP.md, .cursor/rules/assistant.mdc, AGENTS.md and the tool
// matrix). Every consumer — `base build`, `base init`, the committed starters — calls THESE
// renderers; none carries a copy.
//
// The files are GENERATED by `base build` from the language table below and gated for freshness in
// CI, so they cannot drift. The policy is deliberately **agent-agnostic**: the entry point is a
// router rather than an identity, and never hard-codes a default agent. Routing happens at task
// boundaries (or on `R`), and the READER routes: it descends the generated index and chooses on
// «Quand l'utiliser». The deterministic lexical decision serves callers with no model (script,
// integration, route-test) and accompanies a model's reading as an indication to verify, so this
// text does not instruct a model to run `base route` (FR-ROUTE-005, and the eval that measures the
// read path, FR-ROUTE-016).
//
// The WORDS live in ./lang/ — one table per language, French the default and the per-key fallback.
// Every renderer takes an optional `lang` and resolves through `stringsFor`; the shape of each file
// (which block follows which, where the banner sits) stays here, because that is structure, not
// language. The module-level ROUTER_INTRO / ROUTER_BODY exports stay French: they are the canonical
// body the eval harness feeds a model and the freshness tests pin verbatim.

import path from "node:path";
import { compareByCodePoint } from "./ordering.mjs";
import { stringsFor } from "./lang/index.mjs";

const FR = stringsFor("fr");

export const ROUTER_INTRO = FR.routerIntro;

export const ROUTER_BODY = FR.routerBody.join("\n");

export function renderClaudeMd(lang) {
  const s = stringsFor(lang);
  return block([
    s.claudeTitle,
    s.provenanceBanner,
    `${s.claudeLead} ${s.routerIntro}`,
    "@.ai/routing/index.md",
    s.routerBody.join("\n"),
  ]);
}

export function renderBootstrapMd(lang) {
  const s = stringsFor(lang);
  return block([
    s.bootstrapTitle,
    s.provenanceBanner,
    `${s.bootstrapLead} ${s.routerIntro}`,
    s.routerBody.join("\n"),
  ]);
}

export function renderCursorRule(lang) {
  const s = stringsFor(lang);
  return block([
    `---\ndescription: ${s.cursorRuleDescription}\nalwaysApply: true\n---`,
    s.provenanceBanner,
    s.routerIntro,
    s.routerBody.join("\n"),
  ]);
}

// The head of AGENTS.md: the canonical body, ending at the catalogue heading. The generated agent list
// is appended by the build (AGENTS.md is both the AGENTS-family bootstrap and the agent catalogue).
export function renderAgentsHeader(lang) {
  const s = stringsFor(lang);
  return block([
    s.agentsTitle,
    s.provenanceBanner,
    s.routerIntro,
    s.routerBody.join("\n"),
    s.agentsCatalogueTitle,
  ]);
}

function block(parts) {
  return parts.join("\n\n");
}

/** AGENTS.md: the canonical router head followed by the agent catalogue, one line per agent. */
export function renderAgentsMd(resources, lang) {
  const s = stringsFor(lang);
  const agents = resources
    .filter((resource) => resource.type === "agent")
    .filter((resource) => {
      const normalized = resource.path.split(path.sep).join("/");
      return normalized.startsWith(".ai/agents/") && !normalized.includes("/_");
    })
    .sort((a, b) => compareByCodePoint(a.path, b.path));

  const lines = [renderAgentsHeader(lang), ""];
  if (agents.length === 0) {
    lines.push(s.agentsEmpty);
  } else {
    for (const agent of agents) {
      const normalized = agent.path.split(path.sep).join("/");
      // Clean agent name = its directory (".ai/agents/<name>/AGENT.md"), not the slugified path id.
      const name = normalized.split("/").slice(-2, -1)[0] || agent.id;
      lines.push(`- **${name}** - ${agent.description || agent.title} → \`${normalized}\``);
    }
  }
  lines.push("");
  return lines.join("\n");
}

// The MCP-phrased routing discipline — ONE source for the guidance a pure-MCP client re-receives on
// every call. English on purpose: MCP tool descriptions are the one BASE surface read by clients that
// never open the French entry files. These constants and the French body above state the same
// discipline; tests pin the constants verbatim (in renderMcpInstructions AND in the route_request
// description), the freshness gate pins the French projections — neither side can drift silently.
// This is why they are NOT in ./lang/: a language table would translate them, and translating them
// is the one thing that must not happen.
export const MCP_ROUTE_DISCIPLINE =
  "route_request returns a `routing_map` (agents -> processes, each with its «Quand l'utiliser»/«Éviter si») to DECIDE from: the deterministic result is a hint to verify, not an order. " +
  "Choose the process whose «Quand l'utiliser» covers the request; open the chosen agent.path then process.path (open_resource) and follow it. " +
  "If nothing fits, ask the returned next_question (or say so), never guess or invent an id; if the result carries `fallback`, load it the same way. Do not re-route on every message: route at task boundaries.";

// How to reach a FACT, as opposed to how to reach a process. The two are different journeys and a
// client that knows only the second reads whole documents to answer a question a passage would have
// answered. Each line below names the cheapest move for one shape of question, in the order a reader
// meets them: an address they already have, a question in ordinary words, a fact, an exploration.
export const MCP_READ_DISCIPLINE =
  "Decide on candidate metadata, never by reading all bodies (discover_resources, or open_resource with projection \"metadata\"). " +
  "Once routed, plan what to preload with get_context_pack (paths and notes, never bodies), then open only what serves. " +
  "To reach a FACT rather than a process: with a known address, open it directly (open_resource, id or id#anchor). " +
  "For a factual question, search at section grain (discover_resources with grain \"section\") and copy the returned refs unchanged into open_resource for the one or two passages that answer it; never substitute the parent id or derive an anchor from its heading. " +
  "To explore what exists, read the map (get_routing_map), not the bodies. " +
  "Several opens in one turn are cheaper than one open of a whole document. " +
  "Cite what you used as id#section, and quote only text you opened, verbatim: a quotation you did not open is an invention.";

export const MCP_CONTINUITY =
  "If you can no longer cite the active process path (a long, summarized conversation), " +
  "re-open agent.path then process.path before acting: the files are the source of truth, not your memory.";

/** The fifth projection of the canonical body: the MCP server `instructions` field, composed from the constants above. */
export function renderMcpInstructions() {
  return [
    "This project is a BASE: agents and processes as plain files. You are the router, not an identity.",
    MCP_ROUTE_DISCIPLINE,
    MCP_READ_DISCIPLINE,
    MCP_CONTINUITY,
  ].join("\n\n");
}

export function renderToolMatrix(lang) {
  const s = stringsFor(lang);
  return [
    s.toolMatrixTitle,
    "",
    s.toolMatrixBanner,
    "",
    s.toolMatrixLevels,
    "",
    ...s.toolMatrixHonesty,
    "",
    ...s.toolMatrixTable,
    "",
    ...s.toolMatrixFootnotes,
    "",
  ].join("\n");
}
